# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87e15b0716c23560a2565a4905176c529434dd212e787b64f36e22829f424f9cd07788d4b5aa4c741502084fe4281390b79043fca49bd2c5e6d014127a8511a7

test:
  secret_key_base: 5ee45f2cfdac8718f2933640157cc0172b3aef078f4c88e3e87987e6da1d18b46de85d1ab443fe77b49ad4d20dc1b18865dccebcaaba21d91c7ecf573385aea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
